//
// Copyright (c) Phoenix Contact GmbH & Co. KG. All rights reserved.
// Licensed under the MIT. See LICENSE file in the project root for full license information.
// SPDX-License-Identifier: MIT
//
#include "MqttClientServiceProxyFactory.hpp"
#include "MqttClientServiceProxy.hpp"

// DO NOT MODIFY THIS FILE, THIS FILE IS AUTOGENERATED BY IMqttClientService.cs

namespace PxceTcs { namespace MqttClient { namespace Services
{

// initializing of static fields
MqttClientServiceProxyFactory  MqttClientServiceProxyFactory::instance;

MqttClientServiceProxyFactory& MqttClientServiceProxyFactory::GetInstance(void)
{
    return instance;
}

IRscServiceProxy* MqttClientServiceProxyFactory::CreateServiceProxy(RscHandle providerHandle, RscHandle serviceHandle, RscClient& client)
{
    return new MqttClientServiceProxy(providerHandle, serviceHandle, client);
}

}}} // end of namespace PxceTcs::MqttClient::Services
