//
// Copyright (c) Phoenix Contact GmbH & Co. KG. All rights reserved.
// Licensed under the MIT. See LICENSE file in the project root for full license information.
// SPDX-License-Identifier: MIT
//
#pragma once
#include "Arp/System/Rsc/Services/RscServiceProxyFactoryBase.hpp"
#include "Arp/System/Rsc/Services/IRscServiceProxy.hpp"

// DO NOT MODIFY THIS FILE, THIS FILE IS AUTOGENERATED BY IMqttClientService.cs

namespace PxceTcs { namespace MqttClient { namespace Services
{

using namespace Arp::System::Rsc::Services;

class MqttClientServiceProxyFactory : public RscServiceProxyFactoryBase
{
public: // construction/destruction
    /// <summary>Constructs an <see cref="MqttClientServiceProxyFactory" /> instance.</summary>
    MqttClientServiceProxyFactory(void);
    /// <summary>Destructs this instance and frees all resouces.</summary>
    virtual ~MqttClientServiceProxyFactory(void) = default;

public: // static singleton operation
    ARP_CXX_SYMBOL_EXPORT static MqttClientServiceProxyFactory&   GetInstance(void);

public: // IServiceProxyFactory operations
    ARP_CXX_SYMBOL_EXPORT IRscServiceProxy*  CreateServiceProxy(RscHandle providerHandle, RscHandle serviceHandle, RscClient& client)override;

private: // static fields
    static MqttClientServiceProxyFactory  instance;
};

///////////////////////////////////////////////////////////////////////////////
// inline methods of class MqttClientServiceProxyFactory
inline MqttClientServiceProxyFactory::MqttClientServiceProxyFactory()
    : Base("PxceTcs.MqttClient.Services.IMqttClientService", "Pxce")
{
}

}}} // end of namespace PxceTcs::MqttClient::Services

