//
// Copyright (c) Phoenix Contact GmbH & Co. KG. All rights reserved.
// Licensed under the MIT. See LICENSE file in the project root for full license information.
// SPDX-License-Identifier: MIT
//
#include "MqttClientServiceFactory.hpp"
#include "MqttClientServiceImpl.hpp"
#include "MqttClientServiceStub.hpp"
#include "MqttClientServiceSecurityStub.hpp"

// DO NOT MODIFY THIS FILE, THIS FILE IS AUTOGENERATED BY IMqttClientService.cs

namespace PxceTcs { namespace MqttClient { namespace Services
{

// initializing of static fields
MqttClientServiceFactory  MqttClientServiceFactory::instance;

MqttClientServiceFactory::MqttClientServiceFactory(void)
    :RscServiceFactoryBase(false, "Pxce")
{
}

MqttClientServiceFactory& MqttClientServiceFactory::GetInstance(void)
{
    return instance;
}

IRscService* MqttClientServiceFactory::CreateServiceImpl(const char* providerName, IRscAuthorizator* pAuthorizator)
{
    if(this->isSecure)
    {
        return new MqttClientServiceSecurityStub(providerName, pAuthorizator);
    }
    else
    {
        return new MqttClientServiceImpl();
    }
}

IRscServiceStub* MqttClientServiceFactory::CreateServiceStub(const char* providerName, IRscAuthorizator* pAuthorizator)
{
    MqttClientServiceImpl* pImpl = nullptr;
    if(isSecure)
    {
        pImpl = new MqttClientServiceSecurityStub(providerName, pAuthorizator);
    }
    else
    {
        pImpl = new MqttClientServiceImpl();
    }

    return new MqttClientServiceStub(pImpl);
}

}}} // end of namespace PxceTcs::MqttClient::Services
